# All video-level tasks joint training (16 GPU training)
# main setting (R50 video-level joint training)
_BASE_: "../video_joint_r50.yaml" # all video tasks joint training
DATASETS:
  TEST: ("bdd_box_track_val", ) # "bdd_seg_track_val"
INPUT:
  MIN_SIZE_TEST: 800