# All video-level tasks joint training (16 GPU training)
# main setting (R50 video-level joint training)
_BASE_: "../video_joint_r50.yaml" # all video tasks joint training
DATASETS:
  TEST: ("ytvis_ovis_val", )
INPUT:
  MIN_SIZE_TEST: 720 # 720 for ovis