# Step1: Obj365 pretraining (32 GPUs)
MODEL:
  BOXINST:
    ENABLED: True
  USE_IOU_BRANCH: True
  LANG_GUIDE_DET: True
  DECOUPLE_TGT: True
  STILL_TGT_FOR_BOTH: True
  META_ARCHITECTURE: "UNINEXT_IMG"
  WEIGHTS: "weights/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  OTA: True
  STILL_CLS_FOR_ENCODER: True
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res3", "res4", "res5"]
  DDETRS:
    NUM_OBJECT_QUERIES: 900
    TWO_STAGE_NUM_PROPOSALS: 900
    USE_DINO: True
    DYNAMIC_LABEL_ENC: True
    DROPOUT: 0.0
    TWO_STAGE: True
    MIXED_SELECTION: True
    LOOK_FORWARD_TWICE: True
DATASETS:
  TRAIN: ("objects365_v2_train",)
  TEST: ("objects365_v2_val",)
SOLVER:
  IMS_PER_BATCH: 64 # batch-per-gpu = 2 (32GPU training)
  BASE_LR: 0.0002
  VL_LR: 0.0002
  STEPS: (312346,)
  MAX_ITER: 340741 # 1817287 images per epoch. 1817287 x 12 epoch / (2 x 32GPU) 
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 200
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 2500
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 0
  EVAL_AFTER_TRAIN: False
DATALOADER:
  SAMPLER_TRAIN: "ClassAwareSampler"
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
VERSION: 2
OUTPUT_DIR: "outputs/obj365v2_32g_r50"
